#################################################################
# ==> DOWNLOAD APPLICATION AND DATABASE BINARIES FROM NEXUS <== #
#################################################################

- block:
  - name: Clean Old Database Artifacts
    file:
      path: "{{ item }}"
      state: absent
    with_items:
        - "{{ oracle_home }}"
        - "{{ data_top_dir1 }}"
        - "{{ data_top_dir2 }}"
        - "{{ db_archive_dir }}"

  - name: Clean FS1 Application Artifacts
    file:
      path: "{{ app_run_dir }}/EBSapps"
      state: absent

  - name: Clean FS2 Application Artifacts
    file:
      path: "{{ app_patch_dir }}/EBSapps"
      state: absent

  - name: Remove FS1 FMW_Home
    file:
      path: "{{ app_run_dir }}/FMW_Home"
      state: absent

  - name: Remove FS2 FMW_Home
    file:
      path: "{{ app_patch_dir }}/FMW_Home"
      state: absent

  tags: clean
  become: True
  become_user: root

- block:
  - name: Install ACL & EXPECT & RSYNC
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - acl
      - expect
      - rsync
    environment:
      http_proxy: "{{ toll_user }}:{{ toll_password }}@{{ toll_proxy }}"
      https_proxy: "{{ toll_user }}:{{ toll_password }}@{{ toll_proxy }}"

  - name: Create u02 Directory
    file:
      path: '/u02'
      state: directory
      owner: "{{ oracle_user }}"
      group: "{{ oracle_group }}"

  - name: Change u02 Ownership
    file:
      path: '/u02'
      owner: "{{ oracle_user }}"
      group: "{{ oracle_group }}"

  - name: Create /u02/backup Directory
    file:
      path: "/u02/backup"
      state: directory
      owner: "{{ oracle_user }}"
      group: "{{ oracle_group }}"

  tags: create
  become: True
  become_user: root

- block:
  - name: Download Database Artifacts
    shell: 'wget --user={{ repo_username }} --password={{ repo_password }} {{ item.url }} -P {{ item.dir }}'
    with_items:
        - { url: "{{ db_artifact_url }}", dir: "{{ oracle_root_dir }}" }
        - { url: "{{ db_data1_url }}", dir: "{{ oracle_root_dir }}" }
        - { url: "{{ db_data2_url }}", dir: '/u02' }
        - { url: "{{ db_archive_url }}", dir: '/u02/backup' }

  tags: download_db
  become: True
  become_user: "{{ oracle_user }}"

- block:
  - name: Download Application Artifacts
    shell: 'wget --user={{ repo_username }} --password={{ repo_password }} {{ app_artifact_url }} -P {{ app_run_dir }} && chown -R {{ oracle_user }}:{{ oracle_group }} {{ app_run_dir }}'

  tags: download_app
  become: True
  become_user: "{{ oracle_user }}"
