variable user {}
variable password {}
variable domain {}
variable endpoint {}
variable sshkey {}
variable instance_name {}
variable image_list {}
variable image_list_entry {}
variable shape {}
variable boot_storage_size {}
variable storage_size {}
variable ssh_seclist {}
variable http_seclist {}
variable https_seclist {}
variable wls_seclist {}