- block:
  - name: Install Java
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - acl
      - expect
      - rsync
      - java
    environment:
      http_proxy: "{{ toll_user }}:{{ toll_password }}@{{ toll_proxy }}"
      https_proxy: "{{ toll_user }}:{{ toll_password }}@{{ toll_proxy }}"

  tags: java
  become: True
  become_user: root

- block:

  - name: Check existing FTMCLI install directory
    stat:
      path: "{{ ftmcli_install_dir }}"
    register: ftm_dir

  - name: Create FTMCLI install directory
    file:
      path: "{{ ftmcli_install_dir }}"
      state: directory
    when: ftm_dir.stat.exists == False

  - name: Check existing FTMCLI Binaries in {{ ftmcli_install_dir }}
    stat:
      path: "{{ ftmcli_install_dir }}/ftmcli-v2.4.2"
    register: ftm_bin

  - name: Download FTMCLI if not existing
    shell: 'wget --user={{ repo_username }} --password={{ repo_password }} {{ ftmcli_url }} -P {{ ftmcli_install_dir }}'
    when: ftm_bin.stat.exists == False

  - name: Unzip FTMCLI
    unarchive:
      src: '{{ ftmcli_install_dir }}/ftmcli-v2.4.2.zip'
      dest: '{{ ftmcli_install_dir }}'
      remote_src: yes
    when: ftm_bin.stat.exists == False

  tags: ftmcli
  become: True
  become_user: "{{ oracle_user }}"

- block:
  - name: Check existing FTMCLI Properties File
    stat:
      path: "{{ ftmcli_install_dir }}/ftmcli-v2.4.2/ftmcli.properties"
    register: props

  - name: Delete existing Properties File
    file:
      path: '{{ ftmcli_install_dir }}/ftmcli-v2.4.2/ftmcli.properties'
      state: absent
    when: props.stat.exists

  - name: Generate New Properties File
    template:
      src: ftmcli.properties
      dest: "{{ ftmcli_install_dir }}/ftmcli-v2.4.2/ftmcli.properties"
      mode: 0755

  tags: install
  become: True
  become_user: "{{ oracle_user }}"