############################
# Install JAVA Version 1.7 #
############################

- block:
  - name: Install ACL & WGET
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - acl
      - wget

  - name: Download JDK installer from GFTInstallers (Nexus)
    shell: 'wget --user={{ repo_username }} --password={{ repo_password }} {{ jdk_installer_url }} -P /tmp'

  - name: Install Java
    yum:
      name: "/tmp/{{ jdk_installer }}"
      state: present

  - name: Configure Installed Java
    alternatives:
      name: java
      path: "/usr/java/{{ jdk_location }}"
      link: "{{ jdk_symlink }}"

  tags: java
  become: True
  become_user: root